version: '3.4'

services:
  seat-service-mysql:
    build:
      context: ./docker/seat-service
    container_name: seat-service-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'seatservicedb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    # Where our data will be persisted
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    name: seats-data