version: '3.4'

services:
  seat-service-mysql:
    build:
      context: ./docker/seat-service
    container_name: seat-service-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'seatservicedb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    # Where our data will be persisted
    volumes:
      - seat:/var/lib/mysql
  customer-service-mysql:
    build:
      context: ./docker/customer-service
    container_name: customer-service-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'customerservicedb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33067:3306'
    # Where our data will be persisted
    volumes:
      - customer:/var/lib/mysql
  reservation-service-mysql:
    build:
      context: ./docker/reservation-service
    container_name: reservation-service-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'reservationservicedb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33066:3306'
    # Where our data will be persisted
    volumes:
      - reservation:/var/lib/mysql
volumes:
  seat:
    name: seats-data
  customer:
    name: customer-data
  reservation:
    name: reservation-data